version: '3.9'

services:
  db:
    image: postgres
    ports:
      - '54322:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  db-data:
